-- Task: Align academic calendar summaries and events
-- Date: 2026-08-24
-- Tables affected: academic_calendar, academic_events

BEGIN;

ALTER TABLE public.academic_calendar
  ADD COLUMN IF NOT EXISTS ay text,
  ADD COLUMN IF NOT EXISTS total_days integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS weekend_days integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS holidays integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS exam_days integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS weekly_off_days text[] NOT NULL DEFAULT ARRAY['Saturday', 'Sunday'],
  ADD COLUMN IF NOT EXISTS default_teaching_days integer NOT NULL DEFAULT 20;

CREATE UNIQUE INDEX IF NOT EXISTS academic_calendar_year_month_uidx
  ON public.academic_calendar (year, month);

CREATE TABLE IF NOT EXISTS public.academic_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ac_id bigint NOT NULL REFERENCES public.academic_calendar(id) ON DELETE CASCADE,
  start_date date NOT NULL,
  end_date date NOT NULL,
  number_of_days integer GENERATED ALWAYS AS ((end_date - start_date) + 1) STORED,
  event_type text NOT NULL CHECK (event_type IN (
    'student_holiday', 'teacher_holiday', 'examination',
    'exam_preparation', 'teaching_day', 'other'
  )),
  event_name text NOT NULL,
  is_teaching_day boolean NOT NULL DEFAULT false,
  is_student_holiday boolean NOT NULL DEFAULT false,
  is_teacher_holiday boolean NOT NULL DEFAULT false,
  color_code text NOT NULL DEFAULT '#2563eb',
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT academic_events_valid_range CHECK (end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS academic_events_ac_id_idx ON public.academic_events (ac_id);
CREATE INDEX IF NOT EXISTS academic_events_start_date_idx ON public.academic_events (start_date);
CREATE INDEX IF NOT EXISTS academic_events_end_date_idx ON public.academic_events (end_date);
CREATE INDEX IF NOT EXISTS academic_events_type_idx ON public.academic_events (event_type);

ALTER TABLE public.academic_calendar ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.academic_events ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  policy_record record;
BEGIN
  FOR policy_record IN
    SELECT policyname FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'academic_calendar'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.academic_calendar', policy_record.policyname);
  END LOOP;
END;
$$;

CREATE POLICY academic_calendar_read_authenticated ON public.academic_calendar
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS academic_calendar_manage_management ON public.academic_calendar;
CREATE POLICY academic_calendar_manage_management ON public.academic_calendar
  FOR ALL TO authenticated
  USING (has_role_above(16))
  WITH CHECK (has_role_above(16));

DROP POLICY IF EXISTS academic_events_read_authenticated ON public.academic_events;
CREATE POLICY academic_events_read_authenticated ON public.academic_events
  FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS academic_events_manage_management ON public.academic_events;
CREATE POLICY academic_events_manage_management ON public.academic_events
  FOR ALL TO authenticated
  USING (has_role_above(16))
  WITH CHECK (has_role_above(16));

UPDATE public.academic_calendar
SET total_days = EXTRACT(day FROM make_date(year, month, 1) + INTERVAL '1 month - 1 day'),
    weekend_days = (
      SELECT COUNT(*) FROM generate_series(
        make_date(year, month, 1),
        make_date(year, month, 1) + INTERVAL '1 month - 1 day',
        INTERVAL '1 day'
      ) AS day_value
      WHERE EXTRACT(ISODOW FROM day_value) IN (6, 7)
    ),
    weekly_off_days = COALESCE(weekly_off_days, ARRAY['Saturday', 'Sunday']),
    default_teaching_days = COALESCE(default_teaching_days, 20),
    holidays = COALESCE(holidays, 0),
    exam_days = COALESCE(exam_days, 0),
    working_days = COALESCE(working_days, 0),
    teaching_days = COALESCE(teaching_days, 0);

CREATE OR REPLACE FUNCTION public.refresh_academic_calendar_summary(p_ac_id bigint)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  calendar_year integer;
  calendar_month integer;
  month_total integer;
  month_weekends integer;
  event_holidays integer;
  event_exams integer;
  event_teaching integer;
  event_non_teaching integer;
  default_teaching integer;
  weekly_off text[];
BEGIN
  SELECT year, month, default_teaching_days, weekly_off_days
  INTO calendar_year, calendar_month, default_teaching, weekly_off
  FROM public.academic_calendar WHERE id = p_ac_id;
  IF calendar_year IS NULL THEN RETURN; END IF;

  month_total := EXTRACT(day FROM make_date(calendar_year, calendar_month, 1) + INTERVAL '1 month - 1 day');
  month_weekends := (
    SELECT COUNT(*) FROM generate_series(
      make_date(calendar_year, calendar_month, 1),
      make_date(calendar_year, calendar_month, 1) + INTERVAL '1 month - 1 day',
      INTERVAL '1 day'
    ) AS day_value
    WHERE trim(to_char(day_value, 'Day')) = ANY(
      COALESCE(weekly_off, ARRAY['Saturday', 'Sunday'])
    )
  );
  SELECT
    COALESCE(SUM(overlap_days) FILTER (WHERE is_student_holiday OR is_teacher_holiday), 0),
    COALESCE(SUM(overlap_days) FILTER (WHERE event_type = 'examination'), 0),
    COALESCE(SUM(overlap_days) FILTER (WHERE is_teaching_day), 0),
    COALESCE(SUM(overlap_days) FILTER (
      WHERE NOT is_teaching_day AND (
        is_student_holiday OR is_teacher_holiday OR event_type IN ('examination', 'exam_preparation')
      )
    ), 0)
  INTO event_holidays, event_exams, event_teaching, event_non_teaching
  FROM public.academic_events
  CROSS JOIN LATERAL (
    SELECT GREATEST(
      0,
      LEAST(end_date, make_date(calendar_year, calendar_month, 1) + INTERVAL '1 month - 1 day')::date
      - GREATEST(start_date, make_date(calendar_year, calendar_month, 1))::date + 1
    ) AS overlap_days
  ) overlap
  WHERE start_date <= (make_date(calendar_year, calendar_month, 1) + INTERVAL '1 month - 1 day')::date
    AND end_date >= make_date(calendar_year, calendar_month, 1);

  UPDATE public.academic_calendar
  SET total_days = month_total,
      weekend_days = month_weekends,
      holidays = event_holidays,
      exam_days = event_exams,
      working_days = GREATEST(month_total - month_weekends - event_holidays, 0),
      default_teaching_days = COALESCE(default_teaching, 20),
      teaching_days = GREATEST(
        COALESCE(default_teaching, 20) - event_non_teaching + event_teaching,
        0
      ),
      updated_at = timezone('utc'::text, now())
  WHERE id = p_ac_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.refresh_all_academic_calendar_summaries()
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  calendar_row record;
BEGIN
  FOR calendar_row IN SELECT id FROM public.academic_calendar LOOP
    PERFORM public.refresh_academic_calendar_summary(calendar_row.id);
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION public.trigger_refresh_academic_calendar_summary()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  PERFORM public.refresh_all_academic_calendar_summaries();
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS academic_events_refresh_calendar_summary ON public.academic_events;
CREATE TRIGGER academic_events_refresh_calendar_summary
AFTER INSERT OR UPDATE OR DELETE ON public.academic_events
FOR EACH ROW EXECUTE FUNCTION public.trigger_refresh_academic_calendar_summary();

CREATE OR REPLACE FUNCTION public.trigger_refresh_calendar_rules()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF pg_trigger_depth() = 1 THEN
    PERFORM public.refresh_academic_calendar_summary(NEW.id);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS academic_calendar_refresh_rules ON public.academic_calendar;
CREATE TRIGGER academic_calendar_refresh_rules
AFTER UPDATE OF weekly_off_days, default_teaching_days ON public.academic_calendar
FOR EACH ROW EXECUTE FUNCTION public.trigger_refresh_calendar_rules();

DO $$
DECLARE
  calendar_row record;
BEGIN
  FOR calendar_row IN SELECT id FROM public.academic_calendar LOOP
    PERFORM public.refresh_academic_calendar_summary(calendar_row.id);
  END LOOP;
END;
$$;

COMMIT;
