-- Task: Create academic_calendar table + add estimated_periods to map_class_books
-- Date: 2026-08-12
-- Tables affected: academic_calendar, map_class_books

BEGIN;

-- 1. Create academic_calendar table for pacing benchmarks
CREATE TABLE IF NOT EXISTS academic_calendar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year INTEGER NOT NULL,
  month INTEGER NOT NULL CHECK (month >= 1 AND month <= 12),
  working_days INTEGER NOT NULL DEFAULT 22,
  teaching_days INTEGER NOT NULL DEFAULT 20,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(year, month)
);

-- Enable RLS
ALTER TABLE academic_calendar ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read
CREATE POLICY "Allow authenticated read" ON academic_calendar
  FOR SELECT TO authenticated USING (true);

-- Allow authenticated users to write (admin-only enforced at app level)
CREATE POLICY "Allow authenticated write" ON academic_calendar
  FOR ALL TO authenticated USING (has_role_above(16)) WITH CHECK (true);

-- 2. Add estimated_periods column to the class-book mapping table used by the app
ALTER TABLE map_class_books
  ADD COLUMN IF NOT EXISTS estimated_periods INTEGER DEFAULT NULL;

COMMIT;
