-- Task: (1) Create exam_attendance_entries table, (2) Register exam-attendance-upload in app_view_controller,
--        (3) Fix RLS policies to use has_any_role(), (4) Add admission_no to exam_result_entries
-- Date: 2026-10-03
-- Tables affected: exam_attendance_entries, exam_result_entries, app_view_controller

BEGIN;

-- -----------------------------------------------------------------------------
-- SECTION A: Create exam_attendance_entries table (idempotent)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.exam_attendance_entries (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id   BIGINT NOT NULL REFERENCES public.exam_schedules(id) ON DELETE CASCADE,
    admission_no  TEXT NOT NULL,
    present       NUMERIC NOT NULL DEFAULT 0,
    absent        NUMERIC NOT NULL DEFAULT 0,
    on_leave      NUMERIC NOT NULL DEFAULT 0,
    total_days    NUMERIC GENERATED ALWAYS AS (present + absent + on_leave) STORED,
    created_at    TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at    TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT uq_exam_attendance_schedule_adm UNIQUE (schedule_id, admission_no)
);

-- -----------------------------------------------------------------------------
-- SECTION B: RLS for exam_attendance_entries using has_any_role() (not USING(true))
-- -----------------------------------------------------------------------------
ALTER TABLE public.exam_attendance_entries ENABLE ROW LEVEL SECURITY;

-- SELECT: admin, management, coordinator, teacher can read attendance
DROP POLICY IF EXISTS "exam_attendance_read" ON public.exam_attendance_entries;
CREATE POLICY exam_attendance_read ON public.exam_attendance_entries
    FOR SELECT TO authenticated
    USING (
        has_any_role(VARIADIC ARRAY['admin'::text, 'management'::text, 'coordinator'::text, 'teacher'::text])
        OR can_access_component('exam-attendance-upload'::text)
    );

-- INSERT: only admin, management, coordinator can upload attendance
DROP POLICY IF EXISTS "exam_attendance_insert" ON public.exam_attendance_entries;
CREATE POLICY exam_attendance_insert ON public.exam_attendance_entries
    FOR INSERT TO authenticated
    WITH CHECK (
        has_any_role(VARIADIC ARRAY['admin'::text, 'management'::text, 'coordinator'::text])
        OR can_access_component('exam-attendance-upload'::text)
    );

-- UPDATE: same as insert
DROP POLICY IF EXISTS "exam_attendance_update" ON public.exam_attendance_entries;
CREATE POLICY exam_attendance_update ON public.exam_attendance_entries
    FOR UPDATE TO authenticated
    USING (
        has_any_role(VARIADIC ARRAY['admin'::text, 'management'::text, 'coordinator'::text])
        OR can_access_component('exam-attendance-upload'::text)
    )
    WITH CHECK (
        has_any_role(VARIADIC ARRAY['admin'::text, 'management'::text, 'coordinator'::text])
        OR can_access_component('exam-attendance-upload'::text)
    );

-- DELETE: admin and management only
DROP POLICY IF EXISTS "exam_attendance_delete" ON public.exam_attendance_entries;
CREATE POLICY exam_attendance_delete ON public.exam_attendance_entries
    FOR DELETE TO authenticated
    USING (
        has_any_role(VARIADIC ARRAY['admin'::text, 'management'::text])
    );

-- -----------------------------------------------------------------------------
-- SECTION C: Register exam-attendance-upload in app_view_controller
-- -----------------------------------------------------------------------------
INSERT INTO public.app_view_controller
    (component_name, type, display_name, parent_name, valid_access_roles, description, is_active, default_access, display_order)
VALUES
    (
        'exam-attendance-upload',
        'variable',
        'Upload Exam Attendance',
        'exam-results',
        ARRAY['admin', 'management', 'coordinator'],
        'Permission to upload and manage student exam attendance records',
        true,
        'none',
        20
    )
ON CONFLICT (component_name) DO UPDATE
    SET valid_access_roles = EXCLUDED.valid_access_roles,
        description        = EXCLUDED.description,
        is_active          = EXCLUDED.is_active;

-- -----------------------------------------------------------------------------
-- SECTION D: Add admission_no column to exam_result_entries (join key migration)
-- This adds admission_no as a TEXT column mirroring the student unique identifier.
-- Existing rows are backfilled by joining with the students table via student_id.
-- -----------------------------------------------------------------------------

-- Add the column if it does not exist yet
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name   = 'exam_result_entries'
          AND column_name  = 'admission_no'
    ) THEN
        ALTER TABLE public.exam_result_entries
            ADD COLUMN admission_no TEXT;
    END IF;
END;
$$;

-- Backfill admission_no from the students table for all existing rows
UPDATE public.exam_result_entries e
SET    admission_no = s.admission_no
FROM   public.students s
WHERE  e.student_id = s.id
  AND  (e.admission_no IS NULL OR e.admission_no = '');

-- Index for fast lookup by admission_no
CREATE INDEX IF NOT EXISTS idx_exam_result_entries_admission_no
    ON public.exam_result_entries (admission_no);

COMMIT;
