// src/utils/tileRegistry.js
/**
 * UI Metadata Registry for Unified Portal components.
 *
 * NOTE: UI styling and metadata (icon, colors, translations, action handlers)
 * are maintained here in code to keep the database table `app_view_controller`
 * focused strictly on access control, ordering, and activation state.
 */

export const TILE_METADATA_REGISTRY = {
  // ── Admin-only components ──────────────────────────────────────────
  'form-configurations': {
    title: 'Form Configurations',
    description: 'Configure fields, validation, and overrides for dynamic forms in the database.',
    icon: 'fa-sliders-h',
    buttonColor: 'bg-blue-600 text-white',
    shadow: 'shadow-blue-200',
    group: 'admin-only',
    action: 'subview',
  },
  'timetable-planner': {
    title: 'Timetable',
    description: 'View class and teacher schedules, manage classes, subjects, and schedule conflict-free timetables.',
    icon: 'fa-calendar-alt',
    buttonColor: 'bg-brand-primary text-white',
    shadow: 'shadow-brand-lbg',
    group: 'timetable',
    action: 'subview',
  },
  'avc-admin-manager': {
    title: 'View Controller Manager',
    description: 'Manage app_view_controller table — tile visibility, ordering, and access roles.',
    icon: 'fa-cubes',
    buttonColor: 'bg-purple-700 text-white',
    shadow: 'shadow-purple-200',
    group: 'admin-only',
    action: 'subview',
  },

  // ── Shared admin + management components ───────────────────────────
  'employee-management': {
    title: 'Employee Management',
    description: 'Manage employee records, roles, designations, salaries, and bulk imports.',
    icon: 'fa-users-gear',
    buttonColor: 'bg-orange-primary text-white',
    shadow: 'shadow-orange-200',
    group: 'employees',
    action: 'subview',
  },
  'student-records': {
    title: 'Students Management',
    description: 'View and manage student records. Admins have full CRUD; management has read access.',
    icon: 'fa-user-graduate',
    buttonColor: 'bg-green-dark text-white',
    shadow: 'shadow-green-200',
    group: 'students',
    action: 'subview',
  },
  'tv-display': {
    title: 'TV Display Board',
    description: 'Open the full-screen auto-navigating TV display dashboard.',
    icon: 'fa-tv',
    buttonColor: 'bg-emerald-600 text-white',
    shadow: 'shadow-emerald-200',
    group: 'display',
    action: 'open_window',
    actionTarget: '/portal/display',
  },

  // ── Management components ──────────────────────────────────────────
  'registered-complaints': {
    title: 'Registered Complaints',
    description: 'Track and review user complaints and feedback submitted through the portal.',
    icon: 'fa-comments',
    buttonColor: 'bg-amber-600 text-white',
    shadow: 'shadow-amber-200',
    group: 'complaints',
    action: 'subview',
  },
  'timetable-viewer': {
    title: 'Timetable Viewer',
    titleKey: 'role_portal.view_timetable.title',
    description: 'View all class and teacher schedules across the school (read-only).',
    icon: 'fa-calendar-alt',
    buttonColor: 'bg-brand-primary text-white',
    shadow: 'shadow-brand-lbg',
    group: 'timetable',
    action: 'subview',
  },
  'job-applications': {
    title: 'Job Applications',
    description: 'View and review submitted teacher and staff resumes.',
    icon: 'fa-file-signature',
    buttonColor: 'bg-red-600 text-white',
    shadow: 'shadow-red-200',
    group: 'hr',
    action: 'subview',
  },
  'take-test-management': {
    title: 'Take Test Management',
    description: 'Enable/disable test access per candidate mobile number and configure available tests.',
    icon: 'fa-vial',
    buttonColor: 'bg-teal-600 text-white',
    shadow: 'shadow-teal-200',
    group: 'testing',
    action: 'subview',
  },
  'requests-exceptions': {
    title: 'Requests & Exceptions',
    description: 'Review teacher permission requests, exceptions, and track approvals.',
    icon: 'fa-comment-dots',
    buttonColor: 'bg-rose-600 text-white',
    shadow: 'shadow-rose-200',
    group: 'approvals',
    action: 'open_modal',
    actionTarget: 'requests-exceptions',
  },

  // ── Syllabus group — multi-role ────────────────────────────────────
  'syllabus-manager': {
    title: 'Syllabus Manager',
    description: 'Manage curriculum nodes, subjects, books, units, chapters, and lessons.',
    icon: 'fa-book-open',
    buttonColor: 'bg-purple-600 text-white',
    shadow: 'shadow-purple-200',
    group: 'syllabus',
    action: 'subview',
  },
  'lesson-planner-tracker': {
    title: 'Lesson Planner & Tracker',
    description: 'Log daily teaching progress, track syllabus completion, and carry forward lessons.',
    icon: 'fa-chart-line',
    buttonColor: 'bg-blue-600 text-white',
    shadow: 'shadow-blue-200',
    group: 'syllabus',
    action: 'subview',
  },

  // ── Calendar / Dashboard ───────────────────────────────────────────
  'academic-calendar': {
    title: 'Academic Calendar',
    description: 'View or manage holidays, examinations, preparation days, and teaching days.',
    icon: 'fa-calendar-days',
    buttonColor: 'bg-teal-600 text-white',
    shadow: 'shadow-teal-200',
    group: 'calendar',
    action: 'subview',
  },
  'dashboard': {
    title: 'Dashboard',
    description: 'View syllabus progress, activity, and attention-required insights.',
    icon: 'fa-gauge-high',
    buttonColor: 'bg-indigo-600 text-white',
    shadow: 'shadow-indigo-200',
    group: 'dashboard',
    action: 'subview',
  },

  // ── Teacher-only components ────────────────────────────────────────
  'personal-info': {
    title: 'Personal Info',
    description: 'View your employee profile, designation, and update contact information.',
    icon: 'fa-id-card',
    buttonColor: 'bg-emerald-600 text-white',
    shadow: 'shadow-emerald-200',
    group: 'employee',
    action: 'subview',
  },
  'students-viewer': {
    title: 'Students Record',
    description: 'Browse student list and search details (teacher read-only view).',
    icon: 'fa-user-graduate',
    buttonColor: 'bg-brand-primary text-white',
    shadow: 'shadow-brand-lbg',
    group: 'students',
    action: 'subview',
  },

  // ── Shared teacher + parent components ─────────────────────────────
  'my-tickets': {
    title: 'My Tickets',
    description: 'View status and update comments on your submitted support tickets.',
    icon: 'fa-comments',
    buttonColor: 'bg-red-600 text-white',
    shadow: 'shadow-red-200',
    group: 'tickets',
    action: 'subview',
  },

  // ── Parent-only components ─────────────────────────────────────────
  'class-schedule': {
    title: 'Class Schedule',
    titleKey: 'role_portal.class_schedule.title',
    description: 'View the weekly class schedule and timetable for your child.',
    descriptionKey: 'role_portal.class_schedule.description',
    icon: 'fa-calendar-alt',
    buttonColor: 'bg-emerald-600 text-white',
    shadow: 'shadow-emerald-200',
    group: 'timetable',
    action: 'subview',
  },

  // ── Candidate components ───────────────────────────────────────────
  'take-test': {
    title: 'Take Test',
    description: 'Take the online entrance/evaluation test enabled for your mobile number.',
    icon: 'fa-vial',
    buttonColor: 'bg-teal-600 text-white',
    shadow: 'shadow-teal-200',
    group: 'testing',
    action: 'subview',
  },
};

/**
 * Logical grouping labels for filtering and categorization in UI.
 */
export const COMPONENT_GROUPS = {
  all: 'All Features',
  'admin-only': 'Administration',
  employees: 'Staff & Employees',
  students: 'Students',
  timetable: 'Timetable & Schedule',
  syllabus: 'Curriculum & Syllabus',
  calendar: 'Academic Calendar',
  dashboard: 'Dashboard & Reports',
  tickets: 'Support Tickets',
  complaints: 'Complaints',
  hr: 'Recruitment & HR',
  testing: 'Evaluations & Tests',
  approvals: 'Requests & Exceptions',
  display: 'Display Systems',
  'dynamic-form': 'Custom Forms',
};

/**
 * Fallback configuration matching Phase 1 seed rows.
 * Used if `app_view_controller` table has not yet been executed in Supabase SQL editor.
 */
export const FALLBACK_VIEW_CONFIGS = [
  {
    component_name: 'form-configurations',
    component_type: 'tile',
    group_name: 'admin-only',
    is_active: true,
    default_access: 'none',
    description: 'Configure fields, validation, and overrides for dynamic forms in the database.',
    valid_access_roles: ['admin'],
    display_order: 10,
  },
  {
    component_name: 'timetable-planner',
    component_type: 'tile',
    group_name: 'timetable',
    is_active: true,
    default_access: 'none',
    description: 'View class and teacher schedules, manage classes, subjects, and schedule conflict-free timetables.',
    valid_access_roles: ['admin', 'management', 'teacher', 'staff'],
    display_order: 20,
  },
  {
    component_name: 'timetable-viewer',
    component_type: 'component',
    group_name: 'timetable',
    is_active: true,
    default_access: 'none',
    description: 'Timetable View tab (read-only view for class and teacher schedules).',
    valid_access_roles: ['admin', 'management', 'teacher', 'staff'],
    display_order: 21,
  },
  {
    component_name: 'scheduler-setup',
    component_type: 'component',
    group_name: 'timetable',
    is_active: true,
    default_access: 'none',
    description: 'Scheduler Setup tab in Timetable Planner.',
    valid_access_roles: ['admin', 'management', 'staff'],
    display_order: 22,
  },
  {
    component_name: 'teachers-mapping',
    component_type: 'component',
    group_name: 'timetable',
    is_active: true,
    default_access: 'none',
    description: 'Teacher Mapping tab in Timetable Planner.',
    valid_access_roles: ['admin', 'management', 'staff'],
    display_order: 23,
  },
  {
    component_name: 'classes-setup',
    component_type: 'component',
    group_name: 'timetable',
    is_active: true,
    default_access: 'none',
    description: 'Classes Setup tab in Timetable Planner.',
    valid_access_roles: ['admin', 'management'],
    display_order: 24,
  },
  {
    component_name: 'season-setup',
    component_type: 'component',
    group_name: 'timetable',
    is_active: true,
    default_access: 'none',
    description: 'Season Setup tab in Timetable Planner.',
    valid_access_roles: ['admin', 'management'],
    display_order: 25,
  },
  {
    component_name: 'switch-teachers',
    component_type: 'component',
    group_name: 'timetable',
    is_active: true,
    default_access: 'none',
    description: 'Switch Teacher tab in Timetable Planner.',
    valid_access_roles: ['admin', 'management'],
    display_order: 26,
  },
  {
    component_name: 'timetable-sync',
    component_type: 'component',
    group_name: 'timetable',
    is_active: true,
    default_access: 'none',
    description: 'Database Settings & Sync Cog in Timetable Planner.',
    valid_access_roles: ['admin', 'management'],
    display_order: 27,
  },
  {
    component_name: 'timetable-json-config',
    component_type: 'component',
    group_name: 'timetable',
    is_active: true,
    default_access: 'none',
    description: 'Import / Export Timetable JSON Configuration.',
    valid_access_roles: ['admin', 'management'],
    display_order: 28,
  },
  {
    component_name: 'employee-management',
    component_type: 'tile',
    group_name: 'employees',
    is_active: true,
    default_access: 'none',
    description: 'Manage employee records, roles, designations, salaries, and bulk imports.',
    valid_access_roles: ['admin', 'management'],
    display_order: 10,
  },
  {
    component_name: 'student-records',
    component_type: 'tile',
    group_name: 'students',
    is_active: true,
    default_access: 'none',
    description: 'View and manage student records. Admins have full CRUD; management has read access.',
    valid_access_roles: ['admin', 'management'],
    display_order: 20,
  },
  {
    component_name: 'tv-display',
    component_type: 'tile',
    group_name: 'display',
    is_active: true,
    default_access: 'none',
    description: 'Open the full-screen auto-navigating TV display dashboard.',
    valid_access_roles: ['admin', 'management'],
    display_order: 90,
  },
  {
    component_name: 'registered-complaints',
    component_type: 'tile',
    group_name: 'complaints',
    is_active: true,
    default_access: 'none',
    description: 'Track and review user complaints and feedback submitted through the portal.',
    valid_access_roles: ['management'],
    display_order: 30,
  },
  {
    component_name: 'timetable-viewer',
    component_type: 'tile',
    group_name: 'timetable',
    is_active: false,
    default_access: 'none',
    description: 'Legacy Timetable Viewer tile (merged into Timetable tile).',
    valid_access_roles: ['management', 'teacher'],
    display_order: 30,
  },
  {
    component_name: 'job-applications',
    component_type: 'tile',
    group_name: 'hr',
    is_active: true,
    default_access: 'none',
    description: 'View and review submitted teacher and staff resumes.',
    valid_access_roles: ['management'],
    display_order: 40,
  },
  {
    component_name: 'take-test-management',
    component_type: 'tile',
    group_name: 'testing',
    is_active: true,
    default_access: 'none',
    description: 'Enable/disable test access per candidate mobile number and configure available tests.',
    valid_access_roles: ['management'],
    display_order: 50,
  },
  {
    component_name: 'requests-exceptions',
    component_type: 'tile',
    group_name: 'approvals',
    is_active: true,
    default_access: 'none',
    description: 'Review teacher permission requests, exceptions, and track approvals.',
    valid_access_roles: ['management'],
    display_order: 60,
  },
  {
    component_name: 'syllabus-manager',
    component_type: 'tile',
    group_name: 'syllabus',
    is_active: true,
    default_access: 'none',
    description: 'Manage curriculum nodes, subjects, books, units, chapters, and lessons.',
    valid_access_roles: ['admin', 'management', 'teacher'],
    display_order: 10,
  },
  {
    component_name: 'lesson-planner-tracker',
    component_type: 'tile',
    group_name: 'syllabus',
    is_active: true,
    default_access: 'none',
    description: 'Log daily teaching progress, track syllabus completion, and carry forward lessons.',
    valid_access_roles: ['admin', 'management', 'teacher', 'parent'],
    display_order: 20,
  },
  {
    component_name: 'academic-calendar',
    component_type: 'tile',
    group_name: 'calendar',
    is_active: true,
    default_access: 'none',
    description: 'View or manage holidays, examinations, preparation days, and teaching days.',
    valid_access_roles: ['management', 'teacher', 'parent'],
    display_order: 10,
  },
  {
    component_name: 'dashboard',
    component_type: 'tile',
    group_name: 'dashboard',
    is_active: true,
    default_access: 'none',
    description: 'View syllabus progress, activity, and attention-required insights.',
    valid_access_roles: ['management', 'teacher'],
    display_order: 10,
  },
  {
    component_name: 'personal-info',
    component_type: 'tile',
    group_name: 'employee',
    is_active: true,
    default_access: 'none',
    description: 'View your employee profile, designation, and update contact information.',
    valid_access_roles: ['teacher'],
    display_order: 10,
  },
  {
    component_name: 'students-viewer',
    component_type: 'tile',
    group_name: 'students',
    is_active: true,
    default_access: 'none',
    description: 'Browse student list and search details (teacher read-only view).',
    valid_access_roles: ['teacher'],
    display_order: 20,
  },
  {
    component_name: 'my-tickets',
    component_type: 'tile',
    group_name: 'tickets',
    is_active: true,
    default_access: 'none',
    description: 'View status and update comments on your submitted support tickets.',
    valid_access_roles: ['teacher', 'parent'],
    display_order: 10,
  },
  {
    component_name: 'class-schedule',
    component_type: 'tile',
    group_name: 'timetable',
    is_active: true,
    default_access: 'none',
    description: 'View the weekly class schedule and timetable for your child.',
    valid_access_roles: ['parent'],
    display_order: 10,
  },
  {
    component_name: 'take-test',
    component_type: 'tile',
    group_name: 'testing',
    is_active: true,
    default_access: 'none',
    description: 'Take the online entrance/evaluation test enabled for your mobile number.',
    valid_access_roles: ['candidate'],
    display_order: 10,
  },
  {
    component_name: 'avc-admin-manager',
    component_type: 'tile',
    group_name: 'admin-only',
    is_active: true,
    default_access: 'none',
    description: 'Admin UI to manage the app_view_controller table — tile visibility, ordering, and access roles.',
    valid_access_roles: ['admin'],
    display_order: 80,
  },
];
